# NumPy Basics

In [1]:
import numpy as np 

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [2]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [3]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2,3,2))

array([[[0.00000000e+000, 1.00937611e-320],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.04082753e-047]],

       [[4.96396045e-090, 1.48575046e-076],
        [8.40890651e+164, 1.40415776e+165],
        [3.99910963e+252, 1.46030983e-319]]])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Data types for ndarrays

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1, arr2

(array([1., 2., 3.]), array([1, 2, 3], dtype=int32))

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [19]:
float_arr = arr.astype(np.float64)
float_arr, float_arr.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [22]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [23]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .38, .44, .50], dtype=np.float64)

In [24]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [31]:
arr2 > arr 

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [32]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5]

5

In [34]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [37]:
arr_slice[1] = 12345
arr 

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [38]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [40]:
arr2d[0][2]

3

In [41]:
arr2d[0, 2]

3

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
old_values = arr3d[0].copy()

arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[1, 0]

array([7, 8, 9])

In [48]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
x[0]

array([7, 8, 9])

In [51]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [53]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [55]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [56]:
lower_dim_slice.shape

(2,)

In [57]:
arr2d[:2, 2]

array([3, 6])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [60]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [61]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [63]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [64]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [65]:
data[names == 'Bob', 1:]

array([[7],
       [0]])

In [66]:
data[names == 'Bob', 1]

array([7, 0])

In [67]:
names != 'Bob' 

array([False,  True,  True, False,  True,  True,  True])

In [68]:
data[names != 'Bob']

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [69]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [72]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [74]:
data[names != 'Joe'] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing

In [76]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i 
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [77]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [79]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [80]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [81]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [82]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [83]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [84]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr 

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes

In [85]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [88]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, 1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0,  1],
       [ 1,  0,  1]])

In [89]:
np.dot(arr.T, arr)

array([[39, 20, 10],
       [20, 14,  2],
       [10,  2, 10]])

In [90]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0,  1],
       [ 1,  0,  1]])

In [92]:
arr.swapaxes(0,1) == arr.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Pseudorandom Number Generation

In [93]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.72982996,  0.19096331,  0.25391643, -0.85537894],
       [-0.21765594,  1.37321539,  0.42308818,  1.43547069],
       [-0.56709887,  0.49149227,  0.74631056, -0.5516091 ],
       [ 1.31148723,  0.17871167,  0.62472371, -0.70656692]])

In [94]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2,3))

In [95]:
type(rng)

numpy.random._generator.Generator

# Universal Functions: Fast Element-Wise Array Functions

In [97]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [99]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [100]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x, y

(array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
         0.96849691, -0.75938718,  0.90219827]),
 array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
         1.39897899,  1.32229806, -0.29969852]))

In [101]:
np.maximum(x, y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [102]:
arr = rng.standard_normal(7) * 5
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [103]:
remainder, whole_part = np.modf(arr)
remainder, whole_part

(array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
        -0.40843795,  0.62369966]),
 array([ 4., -8., -0.,  2., -6., -0.,  8.]))

In [104]:
arr 

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [105]:
out = np.zeros_like(arr)

In [106]:
np.add(arr, 1)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [107]:
np.add(arr, 1, out=out)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [108]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])